
public class Patters {

	public static void main(String[] args) {
		
		// TODO Autogenerated method stub
		
		for(int i=1;i<=5;i++) {
			for(int j=1;j<=i;j++) {
				
				System.out.print(j);
			
			System.out.print(" ");
			
		}
			System.out.println();	

	}
System.out.println("Demo project assignment for github");
}
}
